Improved combat system
T-aut/adventure-of-a-lifetime pull request #21
Opened 2021-11-11 00:38 UTC by ginterma

Added attack animation for wolf and added push force on meele attacks for both player and wolf. Did not add push force on fireball because it does not work properly for some reason.

2021-11-11 16:45 UTC, MellowJay commented
![](https://github.trello.services/images/mini-trello-icon.png) [[GRAPHICS] Wolf Attack Animation](https://trello.com/c/SKLCW2Mn/121-graphics-wolf-attack-animation)

2021-11-11 16:46 UTC, MellowJay commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FEATURE] Enemy Attack Patterns](https://trello.com/c/Mg8ehybh/55-feature-enemy-attack-patterns)

2021-11-11 17:24 UTC, MellowJay requested changes
Ok, the wolf's attack animations work. Nice.
I'll try to fix the issue with the fireball and the animation property issue.

2021-11-11 17:24 UTC, MellowJay commented on Assets/Scripts/EnemyScritps/EnemyAI.cs
> +        if (myAnimator.GetBool("Attacking") == true)
GetBool() returns a bool value. The "== true" is unnecessary.

2021-11-11 18:58 UTC, MellowJay commented
![image](https://user-images.githubusercontent.com/43152072/141352643-7185e5e1-fe7d-49c7-affa-88a3172655f6.png)

2021-11-11 18:58 UTC, MellowJay approved these changes
The wolf can't be pushed while moving, but I guess this is okay and makes sense.

2021-11-19 23:21 UTC, MellowJay requested changes
I changed the messages a little bit and fixed some spelling mistakes:  
- I wrote the "Press Enter To Proceed" phrase for every God dialog box, because after moving around I didn't know what to press to continue.
- I changed the robot talking about the fireball - it now mentions that pressing the f key casts a fireball, this is accurate on the dev branch, because spacebar performs a dash.  

My feedback on the tutorial experience overall:
- I think the dialog box can be positioned a little bit higher.
- There is a small dark line underneath the robot icon.
- The fire sword, dash and deadly stab maneuvers are not talked about or mentioned.
- I suggest you get the latest changes from dev by renaming your ForestZone scene to TutorialPoC then doing a "git merge dev" in GitBash.

Other than that, the tutorial is awesome! 👍

2021-11-20 11:25 UTC, T-aut approved these changes
Daaaamn this tutorial looks real good 💯. I like the new text, seems to fit the style. I partially agree with @MellowJay on the fact that special attacks are not mentioned in the tutorial. _But it may be the case_ that these attacks should be like a hidden thing - something that the player is taught later on (but skilled players know how to use from the start).

Also the dialog box could be a tad bit higher in the canvas :)

2021-11-21 10:07 UTC, merged